# This file was generated by GoReleaser. DO NOT EDIT.
cask "firmfact" do
  if ::Cask::DSL.method_defined?(:postflight_steps)
    postflight_steps do
      on_macos do
        run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/firmfact"]
      end
    end
  else
    postflight do
      if OS.mac?
        system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/firmfact"]
      end
    end
  end

  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "f5d44c9110d7f2f2a33be34f398caab84ff91edbff8f5d959539e954b4ea7a2c"
      url "https://github.com/firmfact/cli/releases/download/v#{version}/firmfact_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5840a5cf0f3973ba8a699123d318868f85931ee199b0bae05f644fd1dea1209a"
      url "https://github.com/firmfact/cli/releases/download/v#{version}/firmfact_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a8487d0869d8f58eb14904f6b5facfc5f930edecca4b721c5eff11c70c908a15"
      url "https://github.com/firmfact/cli/releases/download/v#{version}/firmfact_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b81fe6bb81aa8892c04782a9f48d6fcbaf0ec715a2f6ba0ddc9025f2e1acc3cd"
      url "https://github.com/firmfact/cli/releases/download/v#{version}/firmfact_#{version}_linux_amd64.tar.gz"
    end
  end

  name "firmfact"
  desc "Sign up, sign in and query your firmfact workspaces from the command line"
  homepage "https://firmfact.com/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "firmfact"
  manpage "manpages/firmfact-ask.1"
  manpage "manpages/firmfact-call.1"
  manpage "manpages/firmfact-claim.1"
  manpage "manpages/firmfact-completion-bash.1"
  manpage "manpages/firmfact-completion-fish.1"
  manpage "manpages/firmfact-completion-powershell.1"
  manpage "manpages/firmfact-completion-zsh.1"
  manpage "manpages/firmfact-completion.1"
  manpage "manpages/firmfact-config-get.1"
  manpage "manpages/firmfact-config-profiles-delete.1"
  manpage "manpages/firmfact-config-profiles-list.1"
  manpage "manpages/firmfact-config-profiles-rename.1"
  manpage "manpages/firmfact-config-profiles.1"
  manpage "manpages/firmfact-config-reset.1"
  manpage "manpages/firmfact-config-set-host.1"
  manpage "manpages/firmfact-config-set.1"
  manpage "manpages/firmfact-config-show.1"
  manpage "manpages/firmfact-config-unset.1"
  manpage "manpages/firmfact-config-use-profile.1"
  manpage "manpages/firmfact-config.1"
  manpage "manpages/firmfact-doctor.1"
  manpage "manpages/firmfact-environment.1"
  manpage "manpages/firmfact-login.1"
  manpage "manpages/firmfact-logout.1"
  manpage "manpages/firmfact-open.1"
  manpage "manpages/firmfact-signup.1"
  manpage "manpages/firmfact-tools-list.1"
  manpage "manpages/firmfact-tools-refresh.1"
  manpage "manpages/firmfact-tools.1"
  manpage "manpages/firmfact-update.1"
  manpage "manpages/firmfact-upload-status.1"
  manpage "manpages/firmfact-upload.1"
  manpage "manpages/firmfact-version.1"
  manpage "manpages/firmfact-whoami.1"
  manpage "manpages/firmfact-workspaces-list.1"
  manpage "manpages/firmfact-workspaces-status.1"
  manpage "manpages/firmfact-workspaces-use.1"
  manpage "manpages/firmfact-workspaces.1"
  manpage "manpages/firmfact.1"
  bash_completion "completions/firmfact.bash"
  fish_completion "completions/firmfact.fish"
  zsh_completion "completions/_firmfact"

  # No zap stanza required
end
